SET SERVEROUTPUT ON;

DECLARE
    CURSOR C_EMPREGADOS IS
        SELECT FIRST_NAME, SALARY FROM HR.EMPLOYEES;

        V_NAME VARCHAR2(30);
        V_SALARY HR.EMPLOYEES.SALARY;
        V_SALARYTOTAL NUMBER (8,2);
BEGIN
    V_TOTAL SALARY:=0;
    OPEN C_EMPLOYEES;
        LOOP
            FETCH C_EMPREGADOS INTO V_NAME, V_SALARY;

            DBMS_OUTPUT.PUT_LINE(V_NAME);
            V_SALARIOTOTAL:=V_SALARIOTOTAL+V_SALARY;

            EXIT WHEN C_EMPREGADOS%NOTFOUND;
        END LOOP;
        DBMS_OUTPUT.PUT_LINE(V_SALARIOTOTAL);

        CLOSE C_EMPLOYEES;
END;

-- Procedures

CREATE OR REPLACE PROCEDURE ADD_NEW_PLAYER
(
    PLAYER_ID_IN IN NUMBER,
    PLAYER_NAME_IN IN VARCHAR2,
    PLAYER_POS_IN IN NUMBER,
    PLAYER_NAME_IN IN VARCHAR2)

IS
BEGIN
    INSERT INTO PLAYER
    (PLAYER_ID, NAME, POSITION, NICKNAME)
    VALUES
    (PLAYER_ID_IN, PLAYER_NAME_IN, PLAYER_POS_IN, PLAYER_NAME_IN);
END;

-- Inserting new information with Procedures.
SELECT * FROM PLAYER;
EXEC ADD_NEW_PLAYER(3, 'PLAYER 3', 99, 'BEGINNER');