SELECT
    *
FROM
    HR.EMPLOYEES;

SELECT
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    SALARY,
    MANAGER_ID
FROM
    HR.EMPLOYEES
WHERE
    MANAGER_ID IN (101, 145, 149);

SELECT
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    SALARY,
    MANAGER_ID
FROM
    HR.EMPLOYEES
WHERE
    MANAGER_ID NOT IN (101, 145, 149);

SELECT
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    SALARY,
    MANAGER_ID
FROM
    HR.EMPLOYEES
WHERE
    FIRST_NAME LIKE '%S%';

SELECT
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    SALARY,
    MANAGER_ID
FROM
    HR.EMPLOYEES
WHERE
    FIRST_NAME NOT LIKE '%S%';

SELECT
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    SALARY,
    MANAGER_ID
FROM
    HR.EMPLOYEES
WHERE
    SALARY BETWEEN 2500 AND 5000;

SELECT
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    SALARY,
    MANAGER_ID
FROM
    HR.EMPLOYEES
WHERE
    SALARY NOT BETWEEN 2500 AND 2600;

INSERT INTO
    PLAYER (PLAYER_ID, NAME, POSITION, NICKNAME)
VALUES
    (1, 'PLAYER 1', 2, 'TACTICAL PLAYER');

INSERT INTO
    CONTRACTOR (PLAYER_ID, START_DATE, END_DATE)
VALUES
    (1, TO_DATE ('09-02-2018'), TO_DATE ('09-02-2019'));

INSERT INTO
    CONSTRACTED (PLAYER_ID, START_DATE, END_DATE)
VALUES
    (2, TO_DATE ('09-02-2020'), TO_DATE ('09-02-2023'));

SELECT
    *
FROM
    PLAYER PLAYER
UPDATE
SET
    NAME = 'ALEXANDER',
    POSITION = 5
WHERE
    PLAYER_ID = 1;

SELECT
    *
FROM
    CONTRACTOR
DELETE FROM CONTRACTOR
WHERE
    PLAYER_ID = 2;